# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Fysioterapeutti Maija-Leena Lehtimäki
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Psykofyysistä fysioterapiaa: Autan sinua löytämään turvallisen tilan kehossasi
footer: Fysioterapeutti Maija-Leena Lehtimäki Y-tunnus 11420481

# GitHub pages
#baseurl: "/maijaleenalehtimaki.fi"
#url: "https://jluttine.github.io"
# Real production domain
baseurl: ""
url: "http://maijaleenalehtimaki.fi"

include: ["_pages"]

date_format: "%e.%-m.%Y"
lang: fi

permalink: /:year:month:day-:title/

# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: "_pages"
    values:
      menu: "main"
