# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Fysioterapeutti Maija-Leena Lehtimäki
#email: your-email@domain.com
description: >
  Rosen-terapeutti, Essential Motion -ohjaaja ja Trauma Releasing Exercises -ohjaaja.
  Psykofyysinen fysioterapia Tampereella.
footer: >
  Fysioterapeutti Maija-Leena Lehtimäki
  <a
  href="https://tietopalvelu.ytj.fi/yritystiedot.aspx?yavain=957313&tarkiste=02BBDBAE25C0ED111F496DC6A50527C6D9536967">
  Y-tunnus 11420481
  </a>

timezone: Europe/Helsinki

# GitHub pages
#baseurl: "/maijaleenalehtimaki.fi"
#url: "https://jluttine.github.io"
# Real production domain
baseurl: ""
url: "http://maijaleenalehtimaki.fi"

include: ["_pages"]

date_format: "%e.%-m.%Y"
lang: fi

permalink: /:year:month:day-:title/

# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: "_posts"
    values:
      layout: "post"
  -
    scope:
      path: "_pages"
    values:
      layout: "page"
      menu: "main"
